### ISSUE TITLE
Standalone mode problem

### ISSUE THREAD

**Issue by EveraertJan** [twobitcircus/rpi-build-and-boot#12]
Hi,

I wanted to get the raspberry into standalone mode, so far the disk is readable by my pc. but when I try to boot it into the raspberry, the boot proces gets stuck on the "can't read file system" error. 
Can you give me more info about what to write in the root file?

So far i've copied the image.img file to the second partition (so the boot stays intact).

best regards

Jan

FYI: thanks for developing this,  saved me a huge amount of building time

**Comment by egradman** [comment]
​"So far i've copied the image.img file to the second partition (so the
boot stays intact).” <— that seems to indicate that you’ve already got a
boot partition on the SD card.  If you’re then writing the entire image.img
file to the second partition, then your SD card looks like this:
“BOOT|BOOT|ROOT”.

Why not just write the entire image.img file to the zero offset of the SD
card?  “dd if=image.img of=/dev/rdiskX bs=1m”

You’ll blow away the boot partition on the SD card, but you’ll be writing
the one in the image.img file.  You’ll need to then modify the config file
to remove the NFS boot options.

On Fri, Feb 27, 2015 at 12:44 AM, Jan Everaert <notifications@github.com>
wrote:

> Hi,
>
> I wanted to get the raspberry into standalone mode, so far the disk is
> readable by my pc. but when I try to boot it into the raspberry, the boot
> proces gets stuck on the "can't read file system" error.
> Can you give me more info about what to write in the root file?
>
> So far i've copied the image.img file to the second partition (so the boot
> stays intact).
>
> best regards
>
> Jan
>
> FYI: thanks for developing this, saved me a huge amount of building time
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twobitcircus/rpi-build-and-boot/issues/12>.
>



-- 
*Eric Gradman*
CTO & Mad Inventor
*P:* 213-268-6253 | *W:* twobitcircus.com <http://www.twobitcircus.com/>
*TW:* @egradman <http://www.twitter.com/egradman>

*TWO BIT CIRCUS*
Engineering Entertainment

Inventors | Developers | Performers

**Comment by EveraertJan** [comment]
That was the.first thing I've tried. The sd became unreadable after that.
Thanx for the quick reply btw

**Comment by egradman** [comment]
That’s unusual.  When you say “unreadable,” do you mean there were no valid
partitions on the card?  Or simply that the card was unbootable?  We know
there are valid partitions on the card, because they’re both mounted in the
virtual machine.

On Fri, Feb 27, 2015 at 11:37 AM, Jan Everaert <notifications@github.com>
wrote:

> That was the.first thing I've tried. The sd became unreadable after that.
> Thanx for the quick reply btw
> On Feb 27, 2015 8:32 PM, "egradman" <notifications@github.com> wrote:
>
> > ​"So far i've copied the image.img file to the second partition (so the
> > boot stays intact).” <— that seems to indicate that you’ve already got a
> > boot partition on the SD card. If you’re then writing the entire
> image.img
> > file to the second partition, then your SD card looks like this:
> > “BOOT|BOOT|ROOT”.
> >
> > Why not just write the entire image.img file to the zero offset of the SD
> > card? “dd if=image.img of=/dev/rdiskX bs=1m”
> >
> > You’ll blow away the boot partition on the SD card, but you’ll be writing
> > the one in the image.img file. You’ll need to then modify the config file
> > to remove the NFS boot options.
> >
> > On Fri, Feb 27, 2015 at 12:44 AM, Jan Everaert <notifications@github.com
> >
> > wrote:
> >
> > > Hi,
> > >
> > > I wanted to get the raspberry into standalone mode, so far the disk is
> > > readable by my pc. but when I try to boot it into the raspberry, the
> boot
> > > proces gets stuck on the "can't read file system" error.
> > > Can you give me more info about what to write in the root file?
> > >
> > > So far i've copied the image.img file to the second partition (so the
> > boot
> > > stays intact).
> > >
> > > best regards
> > >
> > > Jan
> > >
> > > FYI: thanks for developing this, saved me a huge amount of building
> time
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/twobitcircus/rpi-build-and-boot/issues/12>.
> > >
> >
> >
> >
> > --
> > *Eric Gradman*
> > CTO & Mad Inventor
> > *P:* 213-268-6253 | *W:* twobitcircus.com <http://www.twobitcircus.com/>
> > *TW:* @egradman <http://www.twitter.com/egradman>
> >
> > *TWO BIT CIRCUS*
> > Engineering Entertainment
> >
> > Inventors | Developers | Performers
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/twobitcircus/rpi-build-and-boot/issues/12#issuecomment-76456864
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twobitcircus/rpi-build-and-boot/issues/12#issuecomment-76457762>
> .
>



-- 
*Eric Gradman*
CTO & Mad Inventor
*P:* 213-268-6253 | *W:* twobitcircus.com <http://www.twobitcircus.com/>
*TW:* @egradman <http://www.twitter.com/egradman>

*TWO BIT CIRCUS*
Engineering Entertainment

Inventors | Developers | Performers

**Comment by EveraertJan** [comment]
Unreadable for my mac (even with some apps), and unbootable for the
raspberry.
Did i miss some "unmounting" steps?

**Comment by egradman** [comment]
well, I would only expect the boot partition to be readable on the Mac,
unless you have extfs installed.  You could try connecting the drive
directly to the virtual machine and mounting the card there.

The dd MAY have failed because the image file is in use by the virtual
machine.  Try halting the vagrant machine and writing the image to a card.

On Fri, Feb 27, 2015 at 2:54 PM, Jan Everaert <notifications@github.com>
wrote:

> Unreadable for my mac (even with some apps), and unbootable for the
> raspberry.
> Did i miss some "unmounting" steps?
> On Feb 27, 2015 11:50 PM, "egradman" <notifications@github.com> wrote:
>
> > That’s unusual. When you say “unreadable,” do you mean there were no
> valid
> > partitions on the card? Or simply that the card was unbootable? We know
> > there are valid partitions on the card, because they’re both mounted in
> the
> > virtual machine.
> >
> > On Fri, Feb 27, 2015 at 11:37 AM, Jan Everaert <notifications@github.com
> >
> > wrote:
> >
> > > That was the.first thing I've tried. The sd became unreadable after
> that.
> > > Thanx for the quick reply btw
> > > On Feb 27, 2015 8:32 PM, "egradman" <notifications@github.com> wrote:
> > >
> > > > ​"So far i've copied the image.img file to the second partition (so
> the
> > > > boot stays intact).” <— that seems to indicate that you’ve already
> got
> > a
> > > > boot partition on the SD card. If you’re then writing the entire
> > > image.img
> > > > file to the second partition, then your SD card looks like this:
> > > > “BOOT|BOOT|ROOT”.
> > > >
> > > > Why not just write the entire image.img file to the zero offset of
> the
> > SD
> > > > card? “dd if=image.img of=/dev/rdiskX bs=1m”
> > > >
> > > > You’ll blow away the boot partition on the SD card, but you’ll be
> > writing
> > > > the one in the image.img file. You’ll need to then modify the config
> > file
> > > > to remove the NFS boot options.
> > > >
> > > > On Fri, Feb 27, 2015 at 12:44 AM, Jan Everaert <
> > notifications@github.com
> > > >
> > > > wrote:
> > > >
> > > > > Hi,
> > > > >
> > > > > I wanted to get the raspberry into standalone mode, so far the disk
> > is
> > > > > readable by my pc. but when I try to boot it into the raspberry,
> the
> > > boot
> > > > > proces gets stuck on the "can't read file system" error.
> > > > > Can you give me more info about what to write in the root file?
> > > > >
> > > > > So far i've copied the image.img file to the second partition (so
> the
> > > > boot
> > > > > stays intact).
> > > > >
> > > > > best regards
> > > > >
> > > > > Jan
> > > > >
> > > > > FYI: thanks for developing this, saved me a huge amount of building
> > > time
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/twobitcircus/rpi-build-and-boot/issues/12>.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > *Eric Gradman*
> > > > CTO & Mad Inventor
> > > > *P:* 213-268-6253 | *W:* twobitcircus.com <
> > http://www.twobitcircus.com/>
> > > > *TW:* @egradman <http://www.twitter.com/egradman>
> > > >
> > > > *TWO BIT CIRCUS*
> > > > Engineering Entertainment
> > > >
> > > > Inventors | Developers | Performers
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/twobitcircus/rpi-build-and-boot/issues/12#issuecomment-76456864
> > > >
> > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/twobitcircus/rpi-build-and-boot/issues/12#issuecomment-76457762
> > >
> > > .
> > >
> >
> >
> >
> > --
> > *Eric Gradman*
> > CTO & Mad Inventor
> > *P:* 213-268-6253 | *W:* twobitcircus.com <http://www.twobitcircus.com/>
> > *TW:* @egradman <http://www.twitter.com/egradman>
> >
> > *TWO BIT CIRCUS*
> > Engineering Entertainment
> >
> > Inventors | Developers | Performers
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/twobitcircus/rpi-build-and-boot/issues/12#issuecomment-76487908
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twobitcircus/rpi-build-and-boot/issues/12#issuecomment-76488294>
> .
>



-- 
*Eric Gradman*
CTO & Mad Inventor
*P:* 213-268-6253 | *W:* twobitcircus.com <http://www.twobitcircus.com/>
*TW:* @egradman <http://www.twitter.com/egradman>

*TWO BIT CIRCUS*
Engineering Entertainment

Inventors | Developers | Performers

**Comment by EveraertJan** [comment]
Ill try everything your mail states. Would it help to acvtually destroy the
current process? Or would it delete the necessary files?

**Comment by EveraertJan** [comment]
ok. i've tried almost everything. vagrant sure isn't running, i copy the image.img on a freshly formated sd, and even used pibaker. could it be something is wrong with the files i had to adapt, making the sd unreadable?

**Comment by egradman** [comment]
but the image.img can still be used for NFS booting?

On Wed, Mar 11, 2015 at 9:15 AM, Jan Everaert <notifications@github.com>
wrote:

> ok. i've tried almost everything. vagrant sure isn't running, i copy the
> image.img on a freshly formated sd, and even used pibaker. could it be
> something is wrong with the files i had to adapt, making the sd unreadable?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twobitcircus/rpi-build-and-boot/issues/12#issuecomment-78296418>
> .
>



-- 
*Eric Gradman*
CTO & Mad Inventor
*P:* 213-268-6253 | *W:* twobitcircus.com <http://www.twobitcircus.com/>
*TW:* @egradman <http://www.twitter.com/egradman>

*TWO BIT CIRCUS*
Engineering Entertainment

Inventors | Developers | Performers

**Comment by EveraertJan** [comment]
Without issue

**Comment by egradman** [comment]
I just had occasion to test this, and I'm able to make a bootable card from the image.img.  I ran `dd if=image.img of=/dev/rdiskX bs=1m` and once the process completed I modified cmdline.txt to remove the NFS boot stuff.  Its booted now...

**Comment by EveraertJan** [comment]
just to be sure, what does your cmdline.txt and what do i enter here: "On the Raspberry Pi root partition, alter /etc/fstab and restore the mount point for /" 

and (may be a stupid question) i change rdiskX to the appropriate card, right? rdiskX is not supported

**Comment by EveraertJan** [comment]
last call: it bootds, shuts down and boots again, and gets stuk in an nfs boot. so what did you mean by "restore mount point for /"? after this everything might just work

**Comment by egradman** [comment]
Ooh good.  Progress!

Make sure there are no references to NFS in /boot/cmdline.txt.
Also, replace the /etc/fstab with a vanilla one from an ordinary card.


On Tue, Mar 17, 2015 at 3:51 AM, Jan Everaert <notifications@github.com>
wrote:

> last call: it bootds, shuts down and boots again, and gets stuk in an nfs
> boot. so what did you mean by "restore mount point for /"? after this
> everything might just work
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twobitcircus/rpi-build-and-boot/issues/12#issuecomment-82268861>
> .
>



-- 
*Eric Gradman*
CTO & Mad Inventor
*P:* 213-268-6253 | *W:* twobitcircus.com <http://www.twobitcircus.com/>
*TW:* @egradman <http://www.twitter.com/egradman>

*TWO BIT CIRCUS*
Engineering Entertainment

Inventors | Developers | Performers

**Comment by EveraertJan** [comment]
It got fixed. I made a clean install on an sd, without nfs and copied the
fstab to the vagrant one. Everything works just fine now. Thanks a lot for
all the help.

**Comment by egradman** [comment]
AWESOME.  I’ll try to automate this.

On Tue, Mar 17, 2015 at 10:06 AM, Jan Everaert <notifications@github.com>
wrote:

> It got fixed. I made a clean install on an sd, without nfs and copied the
> fstab to the vagrant one. Everything works just fine now. Thanks a lot for
> all the help.
> On Mar 17, 2015 5:43 PM, "egradman" <notifications@github.com> wrote:
>
> > Ooh good. Progress!
> >
> > Make sure there are no references to NFS in /boot/cmdline.txt.
> > Also, replace the /etc/fstab with a vanilla one from an ordinary card.
> >
> >
> > On Tue, Mar 17, 2015 at 3:51 AM, Jan Everaert <notifications@github.com>
> > wrote:
> >
> > > last call: it bootds, shuts down and boots again, and gets stuk in an
> nfs
> > > boot. so what did you mean by "restore mount point for /"? after this
> > > everything might just work
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/twobitcircus/rpi-build-and-boot/issues/12#issuecomment-82268861
> > >
> > > .
> > >
> >
> >
> >
> > --
> > *Eric Gradman*
> > CTO & Mad Inventor
> > *P:* 213-268-6253 | *W:* twobitcircus.com <http://www.twobitcircus.com/>
> > *TW:* @egradman <http://www.twitter.com/egradman>
> >
> > *TWO BIT CIRCUS*
> > Engineering Entertainment
> >
> > Inventors | Developers | Performers
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/twobitcircus/rpi-build-and-boot/issues/12#issuecomment-82465835
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twobitcircus/rpi-build-and-boot/issues/12#issuecomment-82483921>
> .
>



-- 
*Eric Gradman*
CTO & Mad Inventor
*P:* 213-268-6253 | *W:* twobitcircus.com <http://www.twobitcircus.com/>
*TW:* @egradman <http://www.twitter.com/egradman>

*TWO BIT CIRCUS*
Engineering Entertainment

Inventors | Developers | Performers

**Comment by EveraertJan** [comment]
That would seal the deal. Thanks
