### ISSUE TITLE
Using RPi's wifi while being booted through ethernet

### ISSUE THREAD

**Issue by twobeers83** [twobitcircus/rpi-build-and-boot#13]
Hi,

I might be in a rather unique situation, but I wonder if there's a way to use the Raspberry's wifi dongle to get to the internet while having it booted via ethernet from my mac.

My school has a secured wifi network and I'm not able to activate 'Internet Sharing' through the Mac's preference pane. I could however log directly onto the wifi network from my RaspberryPi, but it prefers the ethernet connection to my mac. Is there a way to direct internet (and maybe ssh) requests via the wifi while having it booted through ethernet at the same time?

Thanks,
Tobias

**Comment by egradman** [comment]
This shouldn't be a problem.  You might have to play with `route add default` on the pi (`man route` for more info).  FYI, the virtual machine includes a proxy so you shouldn't have to use Internet Sharing on the mac side at all.
