### ISSUE TITLE
FAILED COMMAND: make $PARALLEL_MAKE all-gcc

### ISSUE THREAD

**Issue by DHaylock** [twobitcircus/rpi-build-and-boot#16]
Hey @egradman,

Getting a really odd error.

```
echo | /tmp/CROSS_BUILD_TOOLS/build-gcc/./gcc/xgcc -B/tmp/CROSS_BUILD_TOOLS/build-gcc/./gcc/ -E -dM - | \
	  sed -n -e 's/^#define \([^_][a-zA-Z0-9_]*\).*/\1/p' \
		 -e 's/^#define \(_[^_A-Z][a-zA-Z0-9_]*\).*/\1/p' | \
	  sort -u > tmp-macro_list
/bin/bash ../../gcc-4.9.2/gcc/../move-if-change tmp-macro_list macro_list
echo timestamp > s-macro_list
rm -rf include-fixed; mkdir include-fixed
chmod a+rx include-fixed
if [ -d ../prev-gcc ]; then \
	  cd ../prev-gcc && \
	  make real-install-headers-tar DESTDIR=`pwd`/../gcc/ \
	    libsubdir=. ; \
	else \
	  set -e; for ml in `cat fixinc_list`; do \
	    sysroot_headers_suffix=`echo ${ml} | sed -e 's/;.*$//'`; \
	    multi_dir=`echo ${ml} | sed -e 's/^[^;]*;//'`; \
	    fix_dir=include-fixed${multi_dir}; \
	    if ! false && test ! -d `echo /opt/RPI_BUILD_ROOT${sysroot_headers_suffix}/usr/include | sed -e :a -e 's,[^/]*/\.\.\/,,' -e ta`; then \
	      echo The directory that should contain system headers does not exist: >&2 ; \
	      echo "  `echo /opt/RPI_BUILD_ROOT${sysroot_headers_suffix}/usr/include | sed -e :a -e 's,[^/]*/\.\.\/,,' -e ta`" >&2 ; \
	      tooldir_sysinc=`echo "/opt/cross/lib/gcc/arm-linux-gnueabihf/4.9.2/../../../../arm-linux-gnueabihf/sys-include" | sed -e :a -e "s,[^/]*/\.\.\/,," -e ta`; \
	      if test "x`echo /opt/RPI_BUILD_ROOT${sysroot_headers_suffix}/usr/include | sed -e :a -e 's,[^/]*/\.\.\/,,' -e ta`" = "x${tooldir_sysinc}"; \
	      then sleep 1; else exit 1; fi; \
	    fi; \
	    /bin/bash ../../gcc-4.9.2/gcc/../mkinstalldirs ${fix_dir}; \
	    chmod a+rx ${fix_dir} || true; \
	    (TARGET_MACHINE='arm-unknown-linux-gnueabihf'; srcdir=`cd ../../gcc-4.9.2/gcc; ${PWDCMD-pwd}`; \
	      SHELL='/bin/bash'; MACRO_LIST=`${PWDCMD-pwd}`/macro_list ; \
	      gcc_dir=`${PWDCMD-pwd}` ; \
	      export TARGET_MACHINE srcdir SHELL MACRO_LIST && \
	      cd ../build-x86_64-unknown-linux-gnu/fixincludes && \
	      /bin/bash ./fixinc.sh "${gcc_dir}/${fix_dir}" \
	        `echo /opt/RPI_BUILD_ROOT${sysroot_headers_suffix}/usr/include | sed -e :a -e 's,[^/]*/\.\.\/,,' -e ta`  ); \
	    rm -f ${fix_dir}/syslimits.h; \
	    if [ -f ${fix_dir}/limits.h ]; then \
	      mv ${fix_dir}/limits.h ${fix_dir}/syslimits.h; \
	    else \
	      cp ../../gcc-4.9.2/gcc/gsyslimits.h ${fix_dir}/syslimits.h; \
	    fi; \
	    chmod a+r ${fix_dir}/syslimits.h; \
	  done; \
	fi
rm gcc.pod
make[1]: Leaving directory `/tmp/CROSS_BUILD_TOOLS/build-gcc/gcc'
FAILED COMMAND: make $PARALLEL_MAKE all-gcc

FATAL: all hosts have already failed -- aborting
```

Any Ideas?

**Comment by egradman** [comment]
that’s pretty weird.  Can you dump the whole provisioning output?  I feel
like something must have failed previously.

On Thu, Nov 26, 2015 at 9:34 AM, David Haylock <notifications@github.com>
wrote:

> Hey @egradman <https://github.com/egradman>,
>
> Getting a really odd error.
>
> echo | /tmp/CROSS_BUILD_TOOLS/build-gcc/./gcc/xgcc -B/tmp/CROSS_BUILD_TOOLS/build-gcc/./gcc/ -E -dM - | \
>       sed -n -e 's/^#define \([^_][a-zA-Z0-9_]*\).*/\1/p' \
>          -e 's/^#define \(_[^_A-Z][a-zA-Z0-9_]*\).*/\1/p' | \
>       sort -u > tmp-macro_list
> /bin/bash ../../gcc-4.9.2/gcc/../move-if-change tmp-macro_list macro_list
> echo timestamp > s-macro_list
> rm -rf include-fixed; mkdir include-fixed
> chmod a+rx include-fixed
> if [ -d ../prev-gcc ]; then \
>       cd ../prev-gcc && \
>       make real-install-headers-tar DESTDIR=`pwd`/../gcc/ \
>         libsubdir=. ; \
>     else \
>       set -e; for ml in `cat fixinc_list`; do \
>         sysroot_headers_suffix=`echo ${ml} | sed -e 's/;.*$//'`; \
>         multi_dir=`echo ${ml} | sed -e 's/^[^;]*;//'`; \
>         fix_dir=include-fixed${multi_dir}; \
>         if ! false && test ! -d `echo /opt/RPI_BUILD_ROOT${sysroot_headers_suffix}/usr/include | sed -e :a -e 's,[^/]*/\.\.\/,,' -e ta`; then \
>           echo The directory that should contain system headers does not exist: >&2 ; \
>           echo "  `echo /opt/RPI_BUILD_ROOT${sysroot_headers_suffix}/usr/include | sed -e :a -e 's,[^/]*/\.\.\/,,' -e ta`" >&2 ; \
>           tooldir_sysinc=`echo "/opt/cross/lib/gcc/arm-linux-gnueabihf/4.9.2/../../../../arm-linux-gnueabihf/sys-include" | sed -e :a -e "s,[^/]*/\.\.\/,," -e ta`; \
>           if test "x`echo /opt/RPI_BUILD_ROOT${sysroot_headers_suffix}/usr/include | sed -e :a -e 's,[^/]*/\.\.\/,,' -e ta`" = "x${tooldir_sysinc}"; \
>           then sleep 1; else exit 1; fi; \
>         fi; \
>         /bin/bash ../../gcc-4.9.2/gcc/../mkinstalldirs ${fix_dir}; \
>         chmod a+rx ${fix_dir} || true; \
>         (TARGET_MACHINE='arm-unknown-linux-gnueabihf'; srcdir=`cd ../../gcc-4.9.2/gcc; ${PWDCMD-pwd}`; \
>           SHELL='/bin/bash'; MACRO_LIST=`${PWDCMD-pwd}`/macro_list ; \
>           gcc_dir=`${PWDCMD-pwd}` ; \
>           export TARGET_MACHINE srcdir SHELL MACRO_LIST && \
>           cd ../build-x86_64-unknown-linux-gnu/fixincludes && \
>           /bin/bash ./fixinc.sh "${gcc_dir}/${fix_dir}" \
>             `echo /opt/RPI_BUILD_ROOT${sysroot_headers_suffix}/usr/include | sed -e :a -e 's,[^/]*/\.\.\/,,' -e ta`  ); \
>         rm -f ${fix_dir}/syslimits.h; \
>         if [ -f ${fix_dir}/limits.h ]; then \
>           mv ${fix_dir}/limits.h ${fix_dir}/syslimits.h; \
>         else \
>           cp ../../gcc-4.9.2/gcc/gsyslimits.h ${fix_dir}/syslimits.h; \
>         fi; \
>         chmod a+r ${fix_dir}/syslimits.h; \
>       done; \
>     fi
> rm gcc.pod
> make[1]: Leaving directory `/tmp/CROSS_BUILD_TOOLS/build-gcc/gcc'
> FAILED COMMAND: make $PARALLEL_MAKE all-gcc
>
> FATAL: all hosts have already failed -- aborting
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twobitcircus/rpi-build-and-boot/issues/16>.
>



-- 
*Eric Gradman*
CTO & Mad Inventor
*P:* 213-268-6253 | *W:* twobitcircus.com <http://www.twobitcircus.com/>
*TW:* @egradman <http://www.twitter.com/egradman>

*TWO BIT CIRCUS*
Engineering Entertainment

Inventors | Developers | Performers

**Comment by DHaylock** [comment]
Hey @egradman 

I tried everything i could think of,

[error.txt](https://github.com/twobitcircus/rpi-build-and-boot/files/45280/error.txt)

**Comment by DHaylock** [comment]
Hey @egradman 

Found this amongst the errors 

cc1: error: no include path in which to search for stdc-predef.h
The directory that should contain system headers does not exist:
  /opt/RPI_BUILD_ROOT/usr/include

any clue?

**Comment by egradman** [comment]
yikes.  just pushed.

pull and try again.

On Mon, Nov 30, 2015 at 7:58 AM, David Haylock <notifications@github.com>
wrote:

> Hey @egradman <https://github.com/egradman>
>
> Found this amongst the errors
>
> cc1: error: no include path in which to search for stdc-predef.h
> The directory that should contain system headers does not exist:
> /opt/RPI_BUILD_ROOT/usr/include
>
> any clue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twobitcircus/rpi-build-and-boot/issues/16#issuecomment-160670408>
> .
>



-- 
*Eric Gradman*
CTO & Mad Inventor
*P:* 213-268-6253 | *W:* twobitcircus.com <http://www.twobitcircus.com/>
*TW:* @egradman <http://www.twitter.com/egradman>

*TWO BIT CIRCUS*
Engineering Entertainment

Inventors | Developers | Performers

**Comment by DHaylock** [comment]
cheers 
building now

**Comment by DHaylock** [comment]
Hey @egradman,
Last change worked though have this now.
```
TASK: [lineinfile dest="/home/vagrant/.bash_profile" line="export GST_VERSION=1.0"] *** 
failed: [default] => {"failed": true, "rc": 257}
msg: Destination /home/vagrant/.bash_profile does not exist !
```

**Comment by egradman** [comment]
​pull and try now.  I changed it to add to .profile, which should exist by
default​

On Mon, Nov 30, 2015 at 2:29 PM, David Haylock <notifications@github.com>
wrote:

> Hey @egradman <https://github.com/egradman>,
> Last change worked though have this now.
>
> TASK: [lineinfile dest="/home/vagrant/.bash_profile" line="export GST_VERSION=1.0"] ***
> failed: [default] => {"failed": true, "rc": 257}
> msg: Destination /home/vagrant/.bash_profile does not exist !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twobitcircus/rpi-build-and-boot/issues/16#issuecomment-160782386>
> .
>



-- 
*Eric Gradman*
CTO & Mad Inventor
*P:* 213-268-6253 | *W:* twobitcircus.com <http://www.twobitcircus.com/>
*TW:* @egradman <http://www.twitter.com/egradman>

*TWO BIT CIRCUS*
Engineering Entertainment

Inventors | Developers | Performers

**Comment by DHaylock** [comment]
Hero!!! Cheers fella
