### ISSUE TITLE
/vagrant not mounting (sometimes)

### ISSUE THREAD

**Issue by bakercp** [twobitcircus/rpi-build-and-boot#6]
My current solution, which seems to be working is to install this plugin:

`vagrant plugin install vagrant-vbguest`

It makes sure that all of the guest additions are up-to-date.

If this is not just an issue that resulted from a misconfiguration on my end, perhaps we should add this plugin installation to the setup or setup instructions?

**Comment by bakercp** [comment]
Just ran into this again http://talk.olab.io/t/getting-a-raspberry-pi-set-up-to-cross-compile-and-nfs-boot-using-the-method-described-here-github-com-twobitcircus-rpi-build-and-boot/663/25

I don't think it's a problem with this script, but perhaps we could / should include the installation of this plugin as a part of the recipe?

**Comment by bakercp** [comment]
Here are two related issues and possible solutions from the rpi-build-and-boot end.

https://github.com/dotless-de/vagrant-vbguest/issues/117
https://github.com/mitchellh/vagrant/issues/3341

**Comment by egradman** [comment]
The way I’ve addressed this on my end is to mount the loop filesystem from
rc.local.  I owe this project some love.  I’ve made tons of improvements
which I’ll start pushing today.  Hopefully I don’t break all the things.

On Fri, Jan 30, 2015 at 11:20 AM, Christopher Baker <
notifications@github.com> wrote:

> Here are two related issues and possible solutions from the
> rpi-build-and-boot end.
>
> dotless-de/vagrant-vbguest#117
> <https://github.com/dotless-de/vagrant-vbguest/issues/117>
> mitchellh/vagrant#3341 <https://github.com/mitchellh/vagrant/issues/3341>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twobitcircus/rpi-build-and-boot/issues/6#issuecomment-72254830>
> .
>



-- 
*Eric Gradman*
CTO & Mad Inventor
*P:* 213-268-6253 | *W:* twobitcircus.com <http://www.twobitcircus.com/>
*TW:* @egradman <http://www.twitter.com/egradman>

*TWO BIT CIRCUS*
Engineering Entertainment

Inventors | Developers | Performers
